baseURL = "https://pbouillon.github.io/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Pierre Bouillon"
theme = "hermit"
pygmentsCodefences  = true
pygmentsUseClasses  = true
enableEmoji = true

[author]
  name = "Pierre Bouillon"

[blackfriday]
hrefTargetBlank = true
noreferrerLinks = true
nofollowLinks = true

[taxonomies]
  tag = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  themeColor = "#494f5c"

  homeSubtitle = "Software Engineer | Privacy Advocate | Coffee Lover"
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  justifyContent = false

  relatedPosts = false

  code_copy_button = false

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/pierre-bouillon/"

  [[params.social]]
    name = "github"
    url = "https://github.com/pBouillon"

[menu]

  [[menu.main]]
    name = "About me"
    url = "about-me/"
    weight = 10

  [[menu.main]]
    name = "Resume"
    url = "resume/"
    weight = 20
